# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  
    pod 'Firebase/Auth'             # Firebase Authentication
    pod 'Firebase/Firestore'        # Firebase Cloud Firestore
    pod 'Firebase/Storage'
    pod 'FirebaseCore'
    pod 'FirebaseDatabase'
    # Firebase Cloud Storage
       


  # Pods for ChatApplication

  target 'ChatApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatApplicationUITests' do
    # Pods for testing
  end

end
